### ISSUE TITLE
Why Network Usage always show 0 B?

### ISSUE THREAD

**Issue by kukudemajia** [pyrovski/wrtbwmon#28] opened 2017-05-24 03:05 UTC
![qq 20170524085333](https://cloud.githubusercontent.com/assets/17118600/26385267/e3f8fe9e-4070-11e7-90bd-1e6009434f85.jpg)

luci-wrtbwmon_0.5.1_all.ipk
wrtbwmon_0.36_all.ipk

**Comment by pyrovski** [comment] 2017-06-11 21:14
This is probably a duplicate of https://github.com/pyrovski/wrtbwmon/issues/23.

**Closed as completed by pyrovski** 2017-06-11 21:14 UTC
