### ISSUE TITLE
Please upstream this

### ISSUE THREAD

**Issue by Strykar** [pyrovski/wrtbwmon#36] opened 2019-11-14 05:40 UTC
This along with https://github.com/Kiougar/luci-wrtbwmon is absolutely brilliant.
Please upstream this?

Starting 19.x onwards, you want to be aware of https://github.com/openwrt/luci/commit/a13748d4145edd3edc70e462714a115f7c99470e#diff-ce5e8587ed4408d7875a66815aa383c7L859

Example: `get_wannet()` has been replaced with `get_wan_networks()` that returns a list of upstream interfaces.

**Comment by pyrovski** [comment] 2019-11-30 02:12
Duplicate of https://github.com/pyrovski/wrtbwmon/issues/31.

**Closed as completed by pyrovski** 2019-11-30 02:12 UTC
